### ISSUE TITLE
REST API endpoint randomly fails

### ISSUE THREAD

**Issue by DSuveges** [Ensembl/ensembl-rest#610] opened 2023-10-11 14:41 UTC
Hi guys, I'm trying to retrive variant data from Ensembl's REST API. Most of the time (95%+) things works fine, but I have noticed some of the requests fail by saying:

```json
{
  "error": "Can't call method \"close\" on unblessed reference at /nfs/public/ro/ensweb/live/rest/www_110/ensembl-io/modules/Bio/EnsEMBL/IO/TabixParser.pm line 121.\n"
}
```

This is the request:  `https://rest.ensembl.org/variation/human/rs147767607?content-type=application/json;phenotypes=1`

As I said, **most of** the times it works. It fails randomly.

**Comment by EbiArnie** [comment] 2023-10-12 10:49
Hi there!

I tested this query with a few hundred requests, internally and externally.
I'm afraid I could not reproduce this.
Did the query fail for exactly this accession - or could it have been a different one?

I also looked at the code and found an interesting comment - basically, someone ran into such an issue before and applied a fix, but at that time couldn't pinpoint the exact cause.
The fix was in one method, but should be applied to another part too.
So it's possible that this is the same issue, but I'd still like to understand better where this is originating.

If you could shed more light on what you are doing, that would be great. Which accessions, which requests, are there requests in parallel, anything else that might be relevant.

Thanks!

**Comment by DSuveges** [comment] 2023-10-12 12:15
Hi, Thank you so much for getting back to me! I had a bunch of rsIds (~200) to map, most of the time I had no problem getting back the expected response, however there were a few where I got problem:

```
variant: rs34922185, rs34922185
response:
{
  "error": "rs34922185, rs34922185 not found for human"
}
variant: rs58523027
response:
{
  "error": "Can't call method \"close\" on unblessed reference at /nfs/public/ro/ensweb/live/rest/www_110/ensembl-io/modules/Bio/EnsEMBL/IO/TabixParser.pm line 121.\n"
}
variant: rs756441495, rs756441495
response:
{
  "error": "rs756441495, rs756441495 not found for human"
}
variant: rs782470771, rs782470771
response:
{
  "error": "rs782470771, rs782470771 not found for human"
}
variant: rs147767607
response:
{
  "error": "Can't call method \"close\" on unblessed reference at /nfs/public/ro/ensweb/live/rest/www_110/ensembl-io/modules/Bio/EnsEMBL/IO/TabixParser.pm line 121.\n"
}
```
Obviously, where by accident one line contained two rsIDs, the query failed. Then there were these low number of seemingly normal rsids that also failed with the detailed error. If that matters: I was running the queries on a VM in Google cloud.

This was the python function with the query:
```python
def get_mapping(rsid):
    url = f'https://rest.ensembl.org/variation/human/{rsid}?content-type=application/json;phenotypes=1'
    
    data = requests.get(url).json()
    
    # Is there any mapping:
    if ('mappings' not in data) or (len(data['mappings']) == 0):
        print(f'variant: {rsid}')
        print(f'response:\n{json.dumps(data, indent=2)}')
        return ['No mapping at all.']
    
    # Extracting canonical mappings only:
    canonical_mappings = [
        mapping['location'] for mapping in data['mappings'] 
        if mapping["coord_system"] == "chromosome"
    ]

    if len(canonical_mappings) == 0:
        return ["No canonical mapping"]
    else:
        return canonical_mappings
```
I got an infrequent error message when I was requesting data from the browser without the `;phenotypes=1` switch, from EBI, just hitting the refresh button. So no bulk download was going on, just single threaded operation.

**Comment by EbiArnie** [comment] 2023-10-20 15:09
I could now reproduce your issue - thank you.
As you said, it only happens sometimes and not very often. The involved code should be reading from a file, so having this fail sometimes is surprising. I'll try to work my way through our stack.
Meanwhile, I will put in the mentioned fix, but it could be a while before this goes live.

**Comment by DSuveges** [comment] 2023-10-20 17:58
Thank you @EbiArnie for looking into the issue and I'm kind of happy the issue could be reproduced.

**Comment by sgiorgetti** [comment] 2024-07-22 10:53
Closing as got no new follow up since patching

**Closed by sgiorgetti** 2024-07-22 10:53 UTC
