### ISSUE TITLE
BioMart RESTful access Query ERROR: not well-formed (invalid token)

### ISSUE THREAD

**Issue by ossmith** [Ensembl/ensembl-rest#635] opened 2024-03-22 22:02 UTC
I'm trying to test out a wget+XML command to pull gene location information for Drosophila melanogaster from BioMart, but I keep getting errors that I don't quite understand.

System: Attempted on both MacOS Big Sur 11.7.10 and Linux Rocky release 8.6 (Green Obsidian)

Example of what I'm doing:
Input gene IDs: FBgn0261560, FBgn0263846, FBgn0034474, FBgn0036448, FBgn0021750, FBgn0023083
Output attributes: chromosome, start, end, strand, and gene ID

When I get the XML from the web browser, it shows me:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Query>
<Query  virtualSchemaName = "metazoa_mart" formatter = "HTML" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" >
			
	<Dataset name = "dmelanogaster_eg_gene" interface = "default" >
		<Filter name = "ensembl_gene_id" value = "FBgn0261560,FBgn0263846,FBgn0034474,FBgn0036448,FBgn0021750,FBgn0023083"/>
		<Attribute name = "chromosome_name" />
		<Attribute name = "start_position" />
		<Attribute name = "end_position" />
		<Attribute name = "strand" />
		<Attribute name = "ensembl_gene_id" />
	</Dataset>
</Query>
```

But when I run
```
wget -O test 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query virtualSchemaName = "metazoa_mart" formatter = "HTML" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "dmelanogaster_eg_gene" interface = "default" ><Filter name = "ensembl_gene_id" value = "FBgn0261560,FBgn0263846,FBgn0034474,FBgn0036448,FBgn0021750,FBgn0023083"/><Attribute name = "chromosome_name" /><Attribute name = "start_position" /><Attribute name = "end_position" /><Attribute name = "strand" /><Attribute name = "ensembl_metazoa" /></Dataset></Query>\'
```

The test.txt file has only this error:
```
Query ERROR: caught BioMart::Exception: non-BioMart die(): 
not well-formed (invalid token) at line 1, column 560, byte 560 at /nfs/public/ro/ensweb-software/sharedsw/2022_01_17_ct7/linuxbrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/x86_64-linux-thread-multi/XML/Parser.pm line 187.
XML::Simple called at /nfs/public/ro/ensweb/live/mart/www_111/biomart-perl/lib/BioMart/Query.pm line 1935.
```

I attempted a couple of variations on that wget call, but they all failed so I suspect I'm not understanding the true nature of the issue.

**Comment by sgiorgetti** [comment] 2024-03-25 09:20
Dear @ossmith ,

Thanks for reaching out and for your patience.

This repository is about the Ensembl [REST API](http://rest.ensembl.org) and not about Biomart, although also the latter one provides RESTful interface. Apologies for the confusion.
For such enquiries, I'd suggest you to join our developers mailing list or - possibly better in your case - contact our Helpdesk. You can find instructions about how to do either of these [HERE](https://www.ensembl.org/info/about/contact/mailing.html)

This said, I tried myself and could successfully retrieve data from Biomart.
There are 2 issues with your command:
1.  There is an unwanted backslash at the end just before the final single quote `\'`. This escapes the final single quote, which is something we do not want, and it's the cause of the "malformed error".
2. You are using the metazoan mart ... which makes sense in general, but for some reasons we put Drosophila M. among vertebrates and the "link" from Metazoa does not work 😞 . And this is definitely not anything you can fix. I am flagging this up internally.

As temporary solution - after having removed the offending `\` - you may want to use the Drosophila melanogaster mart from the vertebrates [HERE](https://www.ensembl.org/biomart/martview).

The cmd line I used was 
```
wget -O result.txt 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "dmelanogaster_gene_ensembl" interface = "default" ><Filter name = "ensembl_gene_id" value = "FBgn0261560,FBgn0263846,FBgn0034474"/><Attribute name = "ensembl_gene_id" /><Attribute name = "chromosome_name" /><Attribute name = "start_position" /><Attribute name = "end_position" /><Attribute name = "strand" /></Dataset></Query>'
```
and the XML was
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Query>
<Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" >
	<Dataset name = "dmelanogaster_gene_ensembl" interface = "default" >
		<Filter name = "ensembl_gene_id" value = "FBgn0261560,FBgn0263846,FBgn0034474"/>
		<Attribute name = "ensembl_gene_id" />
		<Attribute name = "chromosome_name" />
		<Attribute name = "start_position" />
		<Attribute name = "end_position" />
		<Attribute name = "strand" />
	</Dataset>
</Query>
```

Closing this issue as it's not pertinent to this repository.
Any further questions, please do not hesitate to ask our Helpdesk, and feel free to mention me ... this might expedite my involvement, if needed 😄

**Closed** 2024-03-25 09:20 UTC

**Comment by ossmith** [comment] 2024-03-26 14:41
@sgiorgetti Thanks very much! Both for the command help and for flagging the Metazoa mismatch.
